services:
  e2e:
    build:
      context: .
      dockerfile: docker/e2e/Dockerfile
    environment:
      - API_BASE_URL=http://front:5173
    ports:
      - "9323:9323"
    networks:
      - e2e_test_network
    depends_on:
      go:
        condition: service_healthy
      front:
        condition: service_healthy
    hostname: e2e
    tty: "true"

  front:
    build:
      context: .
      dockerfile: docker/front_ci/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      go:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5173/todo"]
      interval: 5s
      timeout: 60s
      retries: 15
      start_period: 10s
    networks:
      - e2e_test_network
    tty: "true"

  go:
    build:
      context: .
      dockerfile: docker/go_ci/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./go/.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/api/v1/test"]
      interval: 5s
      timeout: 60s
      retries: 15
      start_period: 10s
    networks:
      - db_network
      - e2e_test_network
    tty: "true"

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      LC_ALL: ja_JP.UTF-8
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "-e", "USE ${MYSQL_DATABASE};"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 10s
    ports:
      - "3306:3306"
    networks:
      - db_network

networks:
  db_network:
  e2e_test_network: