name: backend-test
on:
  workflow_call:

jobs:
  backcend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Cache Go go_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - run: cd go && go mod download
      - run: cd go && go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - run: cd go && golangci-lint run
      - run: cd go && go fmt ./...
      - run: cd go && go test ./...