name: CI main pull request

on:
  pull_request:
    branches:
      - main

jobs:
  call-e2e-test:
    uses: ./.github/workflows/e2e_test.yml
  call-backend-test:
    uses: ./.github/workflows/backend_test.yml

  call-frontend-test:
    uses: ./.github/workflows/frontend_test.yml